name: TreeOfThoughtsAgent
architecture: custom
sub_agents:
  - name: ThoughtGenerator
    model: gemini-2.5-flash-lite
    instruction: "You are a thought generator. Your job is to generate a list of possible next steps or thoughts to explore to solve the user's request, based on the current path: {current_path}."
    output_key: "thoughts"
  - name: StateEvaluator
    model: gemini-2.5-flash-lite
    instruction: "You are a state evaluator. Your job is to evaluate the current state of the solution and the generated thoughts: {thoughts}. You should prune the thoughts that are not promising and select the best one to explore next. Respond with a JSON object with a 'best_thought' field."
    output_key: "best_thought"
  - name: ResponseGenerator
    model: gemini-2.5-flash-lite
    instruction: "You are a response generator. Your job is to generate a final response to the user's request, based on the final path: {final_path}."
    output_key: "response"
