name: BlackboardSequentialAgent
architecture: sequential
sub_agents:
  - name: Controller
    model: gemini-2.5-flash-lite
    instruction: |
      You are the Controller. Your job is to analyze the user's request and the conversation history to create a step-by-step plan.
      The Worker agent will execute this plan.
      Output ONLY the plan.

  - name: Worker
    model: gemini-2.5-flash-lite
    tools:
      - google_search
    instruction: |
      You are the Worker. You will be given a plan.
      Your job is to execute the *next* step in the plan using your tools.
      Provide a concise summary of the result of the step.
