name: EpisodicWithSemanticAgent
architecture: custom
sub_agents:
  - name: MemoryRetriever
    model: gemini-2.5-flash-lite
    instruction: |
      You are a memory retriever. Your job is to analyze the user's request and the current conversation context.
      Based on this, determine what information from the episodic and semantic memory stores would be relevant.
      Episodic Memory (recent conversation history): {episodic_memory}
      Semantic Memory (knowledge graph): {semantic_memory}
      
      Output a JSON object with a 'retrieved_memories' field, containing a summary of the relevant information.
    output_key: "retrieved_memories"
  - name: ResponseGenerator
    model: gemini-2.5-flash-lite
    instruction: |
      You are a response generator. Your job is to generate a response to the user's request.
      Use the retrieved memories to inform your response.
      Retrieved Memories: {retrieved_memories}
    output_key: "response"
  - name: MemoryUpdater
    model: gemini-2.5-flash-lite
    instruction: |
      You are a memory updater. Your job is to analyze the conversation and extract key information to be stored in the memory stores.
      The conversation is: {conversation_history}
      
      Output a JSON object with two fields:
      - 'episodic': A summary of the last turn of the conversation to be stored in the episodic memory.
      - 'semantic': A list of entities and their relationships to be stored in the semantic memory, in the format ['entity1', 'relationship', 'entity2'].
    output_key: "memory_update"
