name: ToolAgent
architecture: sequential
sub_agents:
  - name: ToolLoop
    architecture: loop
    max_iterations: 5
    sub_agents:
      - name: Thinker
        model: gemini-2.5-flash-lite
        instruction: "You are a thinker. Your job is to analyze the user's request and the conversation history, and decide what action to take. The available actions are to use a tool or to respond to the user. If the user's request involves writing or running code, you must use the 'code_executor' tool. If you decide to use a tool, respond with a JSON object with a 'tool_name' field and a 'tool_input' field. If you decide to respond to the user, respond with a JSON object with a 'response' field."
        output_key: "thought"
      - name: Actor
        model: gemini-2.5-flash-lite
        tools: [google_search, code_executor]
        instruction: "You are an actor. Your job is to execute the action chosen by the thinker: {thought}. If the action is to use a tool, execute the tool and return the result. If the action is to respond to the user, respond to the user."
        output_key: "action_result"
  - name: Synthesizer
    model: gemini-2.5-flash-lite
    instruction: "You are a synthesizer. Your job is to synthesize the final response to the user, based on the action result: {action_result}."
    output_key: "response"
