name: RLHFAgent
architecture: sequential
sub_agents:
  # First: Generate initial draft
  - name: Draft
    model: gemini-2.5-flash-lite
    instruction: |
      You are a draft generator. 
      Create an initial response to the user's request.
      Your draft will be refined through critique and revision.
    tools:
      - google_search
    output_key: "draft"
  
  # Second: Iterative critique-revise loop
  - name: RefinementLoop
    architecture: loop
    max_iterations: 3
    sub_agents:
      - name: CriticReviseSequence
        architecture: sequential
        sub_agents:
          # Critique current draft
          - name: Critic
            model: gemini-2.5-flash-lite
            instruction: |
              You are a critic. Analyze this draft: {draft}
              
              Provide constructive feedback on:
              - Accuracy and completeness
              - Clarity and coherence
              - Areas for improvement
              
              Be specific and actionable.
            output_key: "critique"
          
          # Revise based on critique
          - name: Reviser
            model: gemini-2.5-flash-lite
            instruction: |
              You are a reviser. Improve the draft based on this critique:
              
              Current draft: {draft}
              Critique: {critique}
              
              Create an improved version that addresses the feedback.
            output_key: "draft"
